# Generated by Django 2.1.7 on 2020-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publishedAt', models.DateTimeField()),
                ('thumbUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='cricket',
            index=models.Index(fields=['-publishedAt', 'videoId'], name='youtube_api_publish_f5c0d2_idx'),
        ),
    ]
