# Generated by Django 2.1.7 on 2020-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cricket',
            index=models.Index(fields=['videoId'], name='youtube_api_videoId_01c098_idx'),
        ),
    ]
