# Generated by Django 2.1.7 on 2020-05-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0002_auto_20200510_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='publishedAt',
            field=models.DateTimeField(),
        ),
    ]
